spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/RunSBS/BandFeed-config}
          default-label: ${CONFIG_GIT_BRANCH:main}
          search-paths: configs/{application}
        health:
          enabled: false

server:
  port: 8888
